version: 0.2

phases:
  build:
    commands:
      - zip -r router.zip 01_src/tinyllama/orchestration/lambda_router
  post_build:
    commands:
      - aws lambda update-function-code --function-name tinyllama-router --zip-file fileb://router.zip

artifacts:
  files:
    - router.zip
