name: API – FastAPI + JWT CI

on:
  push:
    paths:
      - "api/**"
      - "02_tests/api/**"
      - ".github/workflows/api_ci.yml"
      - "requirements.txt"
  pull_request:
    paths:
      - "api/**"
      - "02_tests/api/**"

jobs:
  test-and-postman:
    runs-on: ubuntu-latest
    # These secrets and paths are unchanged:
    env:
      COGNITO_USER_POOL_ID:  ${{ secrets.COGNITO_USER_POOL_ID }}
      COGNITO_APP_CLIENT_ID: ${{ secrets.COGNITO_APP_CLIENT_ID }}
      API_BASE_URL:          ${{ secrets.API_BASE_URL }}
      LOCAL_JWKS_PATH:       ${{ github.workspace }}/02_tests/api/data/mock_jwks.json

    steps:
      - uses: actions/checkout@v4

      # ────────────────────────────────────────────────────────────────────────
      # STEP 1: Dynamically load your .env_public into $TLFIF_ENV
      # ────────────────────────────────────────────────────────────────────────
      - name: Load TLFIF_ENV from .env_public
        run: |
          if [ -f .env_public ]; then
            VAL=$(grep -E '^TLFIF_ENV=' .env_public | cut -d= -f2)
            echo "TLFIF_ENV=${VAL:-default}" >> $GITHUB_ENV
          else
            echo "TLFIF_ENV=default" >> $GITHUB_ENV
          fi

      - name: Verify TLFIF_ENV
        run: echo "✅ Using TLFIF_ENV=$TLFIF_ENV"

      # ────────────────────────────────────────────────────────────────────────
      # STEP 2: Set up Python & install dependencies
      # ────────────────────────────────────────────────────────────────────────
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: pytest -q

      # ────────────────────────────────────────────────────────────────────────
      # STEP 3: Run Postman collection
      # ────────────────────────────────────────────────────────────────────────
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run 02_tests/api/postman/API-002.postman_collection.json \
            -e 02_tests/api/postman/tinyllama.postman_env.json \
            --env-var "baseUrl=${{ env.API_BASE_URL }}" \
            --env-var "validJwt=${{ secrets.POSTMAN_VALID_JWT }}" \
            --bail
