name: API – FastAPI + JWT CI

on:
  push:
    paths:
      - "api/**"
      - "02_tests/api/**"
      - ".github/workflows/api_ci.yml"
      - "requirements.txt"
  pull_request:
    paths:
      - "api/**"
      - "02_tests/api/**"

jobs:
  test-and-postman:
    runs-on: ubuntu-latest
    env:
      # real secrets (set once in repo → Settings → Actions → Secrets)
      COGNITO_USER_POOL_ID:  ${{ secrets.COGNITO_USER_POOL_ID }}
      COGNITO_APP_CLIENT_ID: ${{ secrets.COGNITO_APP_CLIENT_ID }}
      API_BASE_URL:          ${{ secrets.API_BASE_URL }}
      # local test helpers
      LOCAL_JWKS_PATH: ${{ github.workspace }}/02_tests/api/data/mock_jwks.json
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install Python Deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: pytest -q

      - uses: actions/setup-node@v3
        with: { node-version: "18" }

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run 02_tests/api/postman/API-002.postman_collection.json \
            -e 02_tests/api/postman/tinyllama.postman_env.json \
            --env-var "baseUrl=${{ env.API_BASE_URL }}" \
            --env-var "validJwt=${{ secrets.POSTMAN_VALID_JWT }}" \
            --bail
