name: API CI

on:
  push:
    paths:
      - "api/**"
      - "tests/**"
      - ".github/workflows/ci.yml"
      - "requirements.txt"
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pytest (expecting failure)
        run: |
          pytest -q
        continue-on-error: false  # pipeline must go red
